### ISSUE TITLE
PDF Delivery

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#50] opened 2016-04-04 17:05 UTC
Good morning, Jeremy,

A close friend in Germany helped me repair the
issue I was having. I recommend the following be
changed in your RACHEL release.

In /usr/local/etc/lighttpd.conf replace this snippet:

mimetype.assign = (
         ".htm"=>"text/html",
         ".html"=>"text/html",
         ".txt"=>"text/plain",
         ".jpg"=>"image/jpeg",
         ".png"=>"image/png",
         ".css"=>"text/css",
         ".js"=>"text/javascript",
         ".gif"=>"image/gif",
         ".mp4"=>"video/mp4",
         ".mp3"=>"audio/mpeg",
         ".svg"=>"image/svg+xml",
         ""=>"application/octet-stream",
)

... with this instead:

mimetype.assign             = (
   ".asc"          =>      "text/plain",
   ".asf"          =>      "video/x-ms-asf",
   ".asx"          =>      "video/x-ms-asf",
   ".avi"          =>      "video/x-msvideo",
   ".bz2"          =>      "application/x-bzip",
   ".c"            =>      "text/plain",
   ".class"        =>      "application/octet-stream",
   ".conf"         =>      "text/plain",
   ".cpp"          =>      "text/plain",
   ".css"          =>      "text/css",
   ".dtd"          =>      "text/xml",
   ".dvi"          =>      "application/x-dvi",
   ".gif"          =>      "image/gif",
   ".gz"           =>      "application/x-gzip",
   ".htm"          =>      "text/html",
   ".html"         =>      "text/html",
   ".jar"          =>      "application/x-java-archive",
   ".jpeg"         =>      "image/jpeg",
   ".jpg"          =>      "image/jpeg",
   ".js"           =>      "text/javascript",
   ".log"          =>      "text/plain",
   ".m3u"          =>      "audio/x-mpegurl",
   ".mov"          =>      "video/quicktime",
   ".mp3"          =>      "audio/mpeg",
   ".mpeg"         =>      "video/mpeg",
   ".mpg"          =>      "video/mpeg",
   ".odc"          =>      "application/vnd.oasis.opendocument.chart",
   ".odf"          =>      "application/vnd.oasis.opendocument.formula",
   ".odg"          =>      "application/vnd.oasis.opendocument.graphics",
   ".odi"          =>      "application/vnd.oasis.opendocument.image",
   ".odm"          =>      "application/vnd.oasis.opendocument.text-master",
   ".odp"          =>      "application/vnd.oasis.opendocument.presentation",
   ".ods"          =>      "application/vnd.oasis.opendocument.spreadsheet",
   ".odt"          =>      "application/vnd.oasis.opendocument.text",
   ".ogg"          =>      "application/ogg",
   ".otc"          =>      "application/vnd.oasis.opendocument.chart-template",
   ".otf"          =>
"application/vnd.oasis.opendocument.formula-template",
   ".otg"          =>
"application/vnd.oasis.opendocument.graphics-template",
   ".oth"          =>      "application/vnd.oasis.opendocument.text-web",
   ".oti"          =>      "application/vnd.oasis.opendocument.image-template",
   ".otp"          =>
"application/vnd.oasis.opendocument.presentation-template",
   ".ots"          =>
"application/vnd.oasis.opendocument.spreadsheet-template",
   ".ott"          =>      "application/vnd.oasis.opendocument.text-template",
   ".pac"          =>      "application/x-ns-proxy-autoconfig",
   ".pdf"          =>      "application/pdf",
   ".png"          =>      "image/png",
   ".ps"           =>      "application/postscript",
   ".qt"           =>      "video/quicktime",
   ".rpm"          =>      "application/x-rpm",
   ".sig"          =>      "application/pgp-signature",
   ".spec"         =>      "text/plain",
   ".spl"          =>      "application/futuresplash",
   ".swf"          =>      "application/x-shockwave-flash",
   ".tar"          =>      "application/x-tar",
   ".tar.bz2"      =>      "application/x-bzip-compressed-tar",
   ".tar.gz"       =>      "application/x-tgz",
   ".tbz"          =>      "application/x-bzip-compressed-tar",
   ".text"         =>      "text/plain",
   ".tgz"          =>      "application/x-tgz",
   ".torrent"      =>      "application/x-bittorrent",
   ".txt"          =>      "text/plain",
   ".wav"          =>      "audio/x-wav",
   ".wax"          =>      "audio/x-ms-wax",
   ".wma"          =>      "audio/x-ms-wma",
   ".wmv"          =>      "video/x-ms-wmv",
   ".xbm"          =>      "image/x-xbitmap",
   ".xml"          =>      "text/xml",
   ".xpm"          =>      "image/x-xpixmap",
   ".xwd"          =>      "image/x-xwindowdump",
   ".zip"          =>      "application/zip",

# make the default mime type application/octet-stream.
       ""              =>      "application/octet-stream",
      )

It is an overkill solution, but it addresses my
one issue and prepares for future better behaviours.

**Comment by spatiald** [comment] 2016-04-04 20:32
Thanks for the feedback!  I'll test it shortly.
Sam

On Apr 4, 2016, at 13:06, Jeremy Schwartz <notifications@github.com> wrote:

Good morning, Jeremy,

A close friend in Germany helped me repair the
issue I was having. I recommend the following be
changed in your RACHEL release.

In /usr/local/etc/lighttpd.conf replace this snippet:

mimetype.assign = (
".htm"=>"text/html",
".html"=>"text/html",
".txt"=>"text/plain",
".jpg"=>"image/jpeg",
".png"=>"image/png",
".css"=>"text/css",
".js"=>"text/javascript",
".gif"=>"image/gif",
".mp4"=>"video/mp4",
".mp3"=>"audio/mpeg",
".svg"=>"image/svg+xml",
""=>"application/octet-stream",
)

... with this instead:

mimetype.assign = (
".asc" => "text/plain",
".asf" => "video/x-ms-asf",
".asx" => "video/x-ms-asf",
".avi" => "video/x-msvideo",
".bz2" => "application/x-bzip",
".c" => "text/plain",
".class" => "application/octet-stream",
".conf" => "text/plain",
".cpp" => "text/plain",
".css" => "text/css",
".dtd" => "text/xml",
".dvi" => "application/x-dvi",
".gif" => "image/gif",
".gz" => "application/x-gzip",
".htm" => "text/html",
".html" => "text/html",
".jar" => "application/x-java-archive",
".jpeg" => "image/jpeg",
".jpg" => "image/jpeg",
".js" => "text/javascript",
".log" => "text/plain",
".m3u" => "audio/x-mpegurl",
".mov" => "video/quicktime",
".mp3" => "audio/mpeg",
".mpeg" => "video/mpeg",
".mpg" => "video/mpeg",
".odc" => "application/vnd.oasis.opendocument.chart",
".odf" => "application/vnd.oasis.opendocument.formula",
".odg" => "application/vnd.oasis.opendocument.graphics",
".odi" => "application/vnd.oasis.opendocument.image",
".odm" => "application/vnd.oasis.opendocument.text-master",
".odp" => "application/vnd.oasis.opendocument.presentation",
".ods" => "application/vnd.oasis.opendocument.spreadsheet",
".odt" => "application/vnd.oasis.opendocument.text",
".ogg" => "application/ogg",
".otc" => "application/vnd.oasis.opendocument.chart-template",
".otf" =>
"application/vnd.oasis.opendocument.formula-template",
".otg" =>
"application/vnd.oasis.opendocument.graphics-template",
".oth" => "application/vnd.oasis.opendocument.text-web",
".oti" => "application/vnd.oasis.opendocument.image-template",
".otp" =>
"application/vnd.oasis.opendocument.presentation-template",
".ots" =>
"application/vnd.oasis.opendocument.spreadsheet-template",
".ott" => "application/vnd.oasis.opendocument.text-template",
".pac" => "application/x-ns-proxy-autoconfig",
".pdf" => "application/pdf",
".png" => "image/png",
".ps" => "application/postscript",
".qt" => "video/quicktime",
".rpm" => "application/x-rpm",
".sig" => "application/pgp-signature",
".spec" => "text/plain",
".spl" => "application/futuresplash",
".swf" => "application/x-shockwave-flash",
".tar" => "application/x-tar",
".tar.bz2" => "application/x-bzip-compressed-tar",
".tar.gz" => "application/x-tgz",
".tbz" => "application/x-bzip-compressed-tar",
".text" => "text/plain",
".tgz" => "application/x-tgz",
".torrent" => "application/x-bittorrent",
".txt" => "text/plain",
".wav" => "audio/x-wav",
".wax" => "audio/x-ms-wax",
".wma" => "audio/x-ms-wma",
".wmv" => "video/x-ms-wmv",
".xbm" => "image/x-xbitmap",
".xml" => "text/xml",
".xpm" => "image/x-xpixmap",
".xwd" => "image/x-xwindowdump",
".zip" => "application/zip",
make the default mime type application/octet-stream.

   ""              =>      "application/octet-stream",
  )

It is an overkill solution, but it addresses my
one issue and prepares for future better behaviours.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/50>

**Comment by spatiald** [comment] 2016-04-06 12:29
Looks like it works without issue.  

My understanding is that the issue is caused by "a number of NBSP characters injected by Eudora."  I'll assume that is correct unless you comment.

**Comment by spatiald** [comment] 2016-04-06 21:39
Noticed an issue...working a fix. 

.mp4 files won't play within browser with new config mentioned above.  Reverted back to the original and all worked fine.

**Comment by spatiald** [comment] 2016-04-07 16:41
Should be fixed in the next update to the USB recovery.

**Closed by spatiald** 2016-04-07 16:41 UTC
Labels: cap, enhancement
