### ISSUE TITLE
v7 USB

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#60] opened 2016-06-03 17:33 UTC
- cap-rachel-configure script is not executable out of the box, forces extra step of making executable
- contentshell is dated (has nov 2015 listed in bottom right and missing stats / version pages), using script options 11, 7 fixes content shell
- KA-Lite install has strange warning about English language
![image](https://cloud.githubusercontent.com/assets/9270388/15787313/75c88190-2976-11e6-9df5-0c1909093963.png)
- Perhaps just my issue, but when running in METHOD="3", I get duplicate index.htmlf files installed at first boot
![image](https://cloud.githubusercontent.com/assets/9270388/15787324/9a73ed2c-2976-11e6-9ec4-b8ee29cebebc.png)

**Comment by j-schwartz** [comment] 2016-06-03 21:51
After then loading the CAP with Kiwix content (in /media/RACHEL/rachel/modules) and rebooting, Kiwix fails to boot

**Comment by spatiald** [comment] 2016-06-03 23:07
? How are you loading kiwix content? Via the content module install
function in the configure script? Or are you just uploading zims?

On Jun 3, 2016, at 17:51, Jeremy Schwartz <notifications@github.com> wrote:

After then loading the CAP with Kiwix content (in
/media/RACHEL/rachel/modules) and rebooting, Kiwix fails to boot

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/60#issuecomment-223703512>,
or mute the thread
<https://github.com/notifications/unsubscribe/AFfEa_aGAtwlWpu4wQ6NcSOt6PnErjeHks5qIKH2gaJpZM4ItvnN>
.

**Comment by j-schwartz** [comment] 2016-06-03 23:23
I'm grabbing them from an external harddrive as full folders.  The issue is
solved by doing this, it's just that without the library.xml file in the
spot, it doesn't boot up:

sudo mkdir /media/RACHEL/kiwix
sudo mkdir /media/RACHEL/kiwix/data
sudo mkdir /media/RACHEL/kiwix/data/library
sudo touch /media/RACHEL/kiwix/data/library/library.xml

**Comment by spatiald** [comment] 2016-06-04 00:40
Interesting. The library file should be checked at boot by the startup
script.   I'll check that.

Also, you can use the offline mode to install those files easily. In the
utilities menu, there is a download offline function that will build an
offline repo on your hard drive. Also, using the folder structure I
mentioned before, you can copy your current content to the hard drive so it
doesn't re-download it.

On Jun 3, 2016, at 19:23, Jeremy Schwartz <notifications@github.com> wrote:

I'm grabbing them from an external harddrive as full folders. The issue is
solved by doing this, it's just that without the library.xml file in the
spot, it doesn't boot up:

sudo mkdir /media/RACHEL/kiwix
sudo mkdir /media/RACHEL/kiwix/data
sudo mkdir /media/RACHEL/kiwix/data/library
sudo touch /media/RACHEL/kiwix/data/library/library.xml

On Fri, Jun 3, 2016 at 4:07 PM Sam Kinch <notifications@github.com> wrote:

> ? How are you loading kiwix content? Via the content module install
> function in the configure script? Or are you just uploading zims?
>
> On Jun 3, 2016, at 17:51, Jeremy Schwartz <notifications@github.com>
> wrote:
>
> After then loading the CAP with Kiwix content (in
> /media/RACHEL/rachel/modules) and rebooting, Kiwix fails to boot
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <
>
https://github.com/rachelproject/rachelplus/issues/60#issuecomment-223703512
> >,
> or mute the thread
> <
>
https://github.com/notifications/unsubscribe/AFfEa_aGAtwlWpu4wQ6NcSOt6PnErjeHks5qIKH2gaJpZM4ItvnN
> >
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <
https://github.com/rachelproject/rachelplus/issues/60#issuecomment-223715449
>,
> or mute the thread
> <
https://github.com/notifications/unsubscribe/AI10dBgdbFdt7AxVZ775DYNOUZ0Gj0x7ks5qILO5gaJpZM4ItvnN
>
> .
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/60#issuecomment-223717433>,
or mute the thread
<https://github.com/notifications/unsubscribe/AFfEaxBeFfE2X0vwva3Zq7fQPVaSvsoBks5qILdhgaJpZM4ItvnN>
.

**Comment by j-schwartz** [comment] 2016-06-09 19:13
in rachel-files/modules there are two folders kalite and local_content without the new naming structure. I deleted those files from the USB and ran createUSB.sh

The script grabbed the new versions of those files, but also started to grab all of the content within en-kalite/content/*


[*] Setting the recovery method to '1' for the default recovery method.

[*] Adding the local_content module.
receiving incremental file list
rsync: symlink "/media/usbhd-sdb1/rachel-files/contentshell/modules/en-local_content/index.htmlf" -> "rachel-index.php" failed: Operation not permitted (1)
en-local_content/
en-local_content/intro.mp4
en-local_content/lesson_planner.png
en-local_content/rachel-index.php

sent 93 bytes  received 37865463 bytes  4454771.29 bytes/sec
total size is 37852446  speedup is 1.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1536) [generator=3.0.9]

[*] Adding the ka-lite module.
receiving incremental file list
rsync: symlink "/media/usbhd-sdb1/rachel-files/contentshell/modules/en-kalite/index.htmlf" -> "rachel-index.php" failed: Operation not permitted (1)
en-kalite/
en-kalite/content_khan_en.sqlite
en-kalite/install.sh
en-kalite/ka.png
en-kalite/rachel-index.php
en-kalite/content/
en-kalite/content/--VYlmbkzNY.mp4
en-kalite/content/--ezF4qkjxg.mp4
en-kalite/content/-05OfTp6ZEE.mp4
en-kalite/content/-0zm323sehQ.mp4
en-kalite/content/-1KeL9wVfOY.mp4
en-kalite/content/-1ZFVwMXSXY.mp4
en-kalite/content/-1w9RXhCmsE.mp4
en-kalite/content/-3DFzxbP9Fk.mp4
en-kalite/content/-4kGMI-qQ3I.mp4
en-kalite/content/-4s4vYJnIW4.mp4
en-kalite/content/-6EqUILZ1yw.mp4
en-kalite/content/-6Fu2T_RSGM.mp4
en-kalite/content/-6KzZKuQ1lk.mp4
^Crsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(549) [generator=3.0.9]

[*] Unmounting USB.
rsync error: received SIGUSR1 (code 19) at main.c(1316) [receiver=3.0.9]
umount: /dev/sdb: not mounted
umount: /dev/sdb2: not mounted

[*] Creating image of USB drive (on USB 2.0 = ~55min; on USB 3.0 = ~2min20sec).
File location:  /media/RACHEL/recovery/RACHEL_Recovery_USB_1-2-16_v7f_20160609.img

**Comment by spatiald** [comment] 2016-06-29 05:22
I think I fixed most of the errors that you were experiencing on the cap
configure script.  Please update your current one from github and give it a
try.  You can create an updated USB recovery as well.  I will be creating
one shortly and uploading to our Drive.

- Stager folder works well; drop the files you want to stage to the USB
staging folder under rachel-files and they will get copied to
/media/RACHEL/staging
- Configure script updates on the CAP and properly changes to executable
- Added check for <kiwix-path>/library.xml and create if missing
- Contentshell updates correctly to the latest (bug in my coding)
- Log files for the usb recovery log to
/var/log/rachel/rachel-runonce-<date>.log
- I believe the duplicate kalite folders should be gone

**Comment by spatiald** [comment] 2016-07-09 12:23
All issues should be resolved in v8 - released/posted 7 July

**Closed** 2016-07-09 12:24 UTC
Labels: usb
